// @ts-check
import eslint from "@eslint/js"
import importX from "eslint-plugin-import-x"
import jest from "eslint-plugin-jest"
import jestExtended from "eslint-plugin-jest-extended"
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended"
import yml from "eslint-plugin-yml"
import globals from "globals"
import tseslint from "typescript-eslint"

export default tseslint.config(
  {
    ignores: [
      // This file.
      "eslint.config.mjs",
      // Jest config files — not part of the typed TS project.
      "**/jest.config.js",
      // Any build output
      "**/dist",
      // Ambient type declarations
      "**/*.d.ts",
      // Generated lockfile — pnpm-managed, not ours to lint/format.
      "**/pnpm-lock.yaml",
      // Workspace yaml — pnpm-managed (writes single-quoted entries when
      // accepting the supply-chain prompt), not ours to lint/format.
      "**/pnpm-workspace.yaml",
      // TypeORM migration files — generated by the typeorm CLI from a
      // separate tsconfig (`apps/bertie/typeorm/tsconfig.json`) and not
      // part of the root TS project service.
      "**/typeorm/migrations/**",
    ],
  },
  eslint.configs.recommended,
  tseslint.configs.recommended,
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
      sourceType: "commonjs",
      parserOptions: {
        projectService: true,
        // Anchor project resolution to this config's directory. Without this,
        // typescript-eslint's project service fails when a single eslint
        // invocation receives files from multiple candidate roots — notably
        // `packages/*` (uses this config) plus `apps/bertie` (uses its own
        // `eslint.config.mjs`). Each config must anchor its own root.
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ["**/*.ts"],
    plugins: {
      "import-x": importX,
    },
    rules: {
      "@typescript-eslint/no-unsafe-argument": "error",
      // Don't use semi-colons to terminate statements.
      semi: ["error", "never"],
      // Force explicitly stated return types to avoid errors where a function returns 2 different types.
      "@typescript-eslint/explicit-function-return-type": "error",
      // Force public, private, protected to be explicitly stated.
      "@typescript-eslint/explicit-member-accessibility": "error",
      // Ensure promises are handled.
      "@typescript-eslint/no-floating-promises": "error",
      // Allow explicit anys as they are often used in request code e.g. when fetching headers.
      "@typescript-eslint/no-explicit-any": "off",
      // Any prettier issues are a lint error.
      "prettier/prettier": ["error"],
      // Prefer `import { type Foo }` syntax — enables tree-shaking and makes type-vs-value intent explicit.
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      // Catch passing async functions where a void callback is expected (common NestJS footgun with event handlers).
      "@typescript-eslint/no-misused-promises": "error",
      // Force handling all union/enum cases in switch — prevents silent bugs when a discriminated union grows.
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      // Ensure `return await` inside try/catch so the async stack trace is preserved.
      "@typescript-eslint/return-await": ["error", "in-try-catch"],
      // Prefer `??` over `||` to avoid falsy-value bugs with `0`, `""`, `false`.
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      // Prefer `a?.b` over `a && a.b` — cleaner and less error-prone.
      "@typescript-eslint/prefer-optional-chain": "error",
      // Barrel-only export tree (#28): historically forbade deep subpath
      // imports via `@neomaventures/request-context/*`. request-context now
      // ships a legitimate `/testing` subpath, so the restriction is lifted.
      // Any future package-internal subpath restrictions live in that
      // package's own eslint override.
      "no-restricted-imports": ["error", { patterns: [] }],
      // Import sorting and organization.
      "import-x/order": [
        "error",
        {
          groups: ["builtin", "external", "internal", "parent", "sibling", "index"],
          "newlines-between": "always",
          alphabetize: { order: "asc" },
        },
      ],
      // Detect circular dependencies.
      "import-x/no-cycle": "error",
      // Prevent duplicate imports. prefer-inline pairs with consistent-type-imports to inline type specifiers.
      "import-x/no-duplicates": ["error", { "prefer-inline": true }],
      // Every runtime import must be a declared dependency or peerDependency.
      // includeTypes catches type-only imports, which still land in the
      // emitted .d.ts and so are part of the published contract.
      "import-x/no-extraneous-dependencies": [
        "error",
        {
          devDependencies: [
            "**/*.spec.ts",
            "e2e/**",
            "eslint.config.mjs",
            "jest.config.js",
          ],
          optionalDependencies: false,
          peerDependencies: true,
          includeTypes: true,
        },
      ],
    },
  },
  // Jest — enforces spec-file best practices (no .only, no conditional expect,
  // valid describe/expect, etc.) via the plugin's recommended preset. Scoped to
  // spec files only; source files are untouched.
  {
    files: ["**/*.spec.ts", "**/*.e2e-spec.ts"],
    ...jest.configs["flat/recommended"],
    plugins: {
      ...jest.configs["flat/recommended"].plugins,
      ...jestExtended.configs["flat/all"].plugins,
    },
    rules: {
      ...jest.configs["flat/recommended"].rules,
      // jest-extended matchers are loaded pack-wide via `jest-extended/all`;
      // the companion plugin's `flat/all` preset enables all 5 rules that
      // push specs toward `toBeTrue`, `toBeFalse`, `toBeArray`, `toBeObject`,
      // and `toHaveBeenCalledOnce`. All 5 rules are autofixable, so the
      // sweep is mechanical. Pre-existing residuals (if any) disabled with
      // TODO(jest-extended#330) markers for per-package follow-up.
      ...jestExtended.configs["flat/all"].rules,
      // Recognise supertest's chained `.expect(...)` as an assertion so e2e
      // specs that end in `request(app).get(...).expect(200)` don't trip the
      // rule. Default `expect` covers jest's global.
      "jest/expect-expect": [
        "warn",
        { assertFunctionNames: ["expect", "request.**.expect"] },
      ],
      // Allow `describe(variableOrConstant, ...)` — several specs derive the
      // describe title from a `LOCATION` const or iterate parameterised
      // fixtures via `.forEach(({ title }) => describe(title, ...))`. The
      // string-type check on it/test titles stays on.
      "jest/valid-title": ["error", { ignoreTypeOfDescribeName: true }],
      // One assertion per `it` block. Multi-field assertions on the same
      // subject should use `toEqual` / `toMatchObject` / `expect.objectContaining`
      // rather than sequential `expect(x.a).toBe(...); expect(x.b).toBe(...)`.
      // Genuinely unrelated behaviours belong in separate `it` blocks.
      // Pre-existing violations disabled inline with TODO(max-expects#317)
      // comments; those cases will be resolved in per-package follow-up PRs.
      "jest/max-expects": ["error", { max: 1 }],
      // Allow `expect(...)` inside `beforeEach` / `afterEach` / `beforeAll` /
      // `afterAll` as a pre-/post-condition assertion. Real-infra e2e specs
      // often boot fixtures whose behaviour IS the setup contract — asserting
      // that in the hook keeps the `it` body focused on the actual claim
      // under test. A failed pre-condition points at the hook, not a test
      // that never ran. `expect` outside any of these blocks still errors.
      "jest/no-standalone-expect": [
        "error",
        {
          additionalTestBlockFunctions: [
            "beforeEach",
            "afterEach",
            "beforeAll",
            "afterAll",
          ],
        },
      ],
      // Allow the `done` callback style. Sync-signature-with-callback shapes
      // (Nest middleware `use(req, res, next)`) read more naturally with
      // `done` than with `await new Promise((resolve) => ...)`. Jest itself
      // still errors within a single test if you mix `async` and `done`, so
      // per-test correctness is guaranteed.
      "jest/no-done-callback": "off",
      // Ban raw fetch() in spec files — use supertest chains
      // (`request(url).get(...).expect(...)`) so response assertions integrate
      // with max-expects: 1 (supertest .expect() calls don't count as jest
      // expects). Supertest works against any HTTP URL, not just Nest apps.
      // Pre-existing violations disabled with TODO(fetch#323) markers.
      "no-restricted-globals": [
        "error",
        {
          name: "fetch",
          message:
            "Use supertest — `request(url).get(...).expect(status).expect(body)` — for HTTP calls in specs. Chainable .expect() integrates with max-expects: 1.",
        },
      ],
      // Close the max-expects back-door: `expect(spy.mock.calls).toEqual(...)`
      // and similar patterns smuggle multiple assertions (count + args) past
      // max-expects by reaching into a spy's internal state. Use jest matchers
      // instead — `toHaveBeenCalledWith` for args, `toHaveBeenCalledTimes` for
      // count, `toHaveBeenCalledExactlyOnceWith` (jest-extended) for both, or
      // split into two `it` blocks with shared setup.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.name='expect'] > MemberExpression[object.property.name='mock']",
          message:
            "Do not assert on spy.mock.* internals — use jest matchers. Args: `toHaveBeenCalledWith`. Count: `toHaveBeenCalledTimes`. Both: `toHaveBeenCalledExactlyOnceWith` (jest-extended) or split into two `it` blocks.",
        },
        // Ban supertest `.expect(callback)` when the callback accesses
        // `res.body` / `res.status` / `res.headers` — supertest has native
        // `.expect(body)`, `.expect(status)`, `.expect(field, value)`
        // signatures that replace them exactly and integrate with
        // max-expects: 1 (nested jest `expect` inside the callback smuggles
        // multiple assertions past the rule). Callback form still allowed
        // for regex/partial matches on other fields (e.g. `res.text`).
        // Pre-existing violations disabled with TODO(supertest-native#331).
        {
          selector:
            "CallExpression[callee.property.name='expect'] ArrowFunctionExpression MemberExpression[object.name='res'][property.name=/^(body|status|headers)$/]",
          message:
            "Use supertest's native .expect() signatures: .expect(body), .expect(status), .expect(field, value). Only use the callback form for assertions supertest can't express natively (regex on dynamic values, partial matches).",
        },
        // Ban `Test.createTestingModule` extracted into a helper function
        // (`buildValidator(config)`, `buildMiddleware(url)`, `setupX(...)`).
        // The `providers` array IS the dependency graph the test documents;
        // hiding it behind an arbitrary function signature makes the reader
        // scroll to a separate function to see what's actually wired. Put
        // setup inline in `beforeEach`. Different scenarios → split describes
        // with their own `beforeEach` — explicit repetition beats hidden
        // variance in a helper's conditional wiring.
        {
          selector:
            ":matches(FunctionDeclaration, VariableDeclarator > :matches(ArrowFunctionExpression, FunctionExpression)) CallExpression[callee.object.name='Test'][callee.property.name='createTestingModule']",
          message:
            "Don't extract Test.createTestingModule into a helper function (buildX, makeX, setupX). Put setup inline in `beforeEach` — the providers array IS the dependency graph the test documents. Different scenarios → split describes with their own `beforeEach`.",
        },
      ],
    },
  },
  // YAML — parses + validates .yml/.yaml (workflows, pnpm-workspace) so a
  // malformed file fails `pnpm lint` locally, before it's pushed. `flat/prettier`
  // defers formatting to prettier (which already runs via the plugin above).
  ...yml.configs["flat/recommended"],
  ...yml.configs["flat/prettier"],
)
